local function set_bg_only(group, bg_color)
	local hl = vim.api.nvim_get_hl(0, { name = group, link = false }) -- 既存の設定を取得
	if hl then
		hl.bg = bg_color -- 背景色のみ変更
		vim.api.nvim_set_hl(0, group, hl) -- 修正後の設定を適用
	end
end

set_bg_only("NormalFloat", "NONE")
set_bg_only("Pmenu", "NONE")
set_bg_only("PmenuSel", "NONE")
set_bg_only("PmenuSbar", "NONE")
set_bg_only("PmenuThumb", "NONE")

set_bg_only("WinBar", "NONE")
set_bg_only("WinBarNC", "NONE")

set_bg_only("TabLineFill", "NONE")

set_bg_only("BufferLineHintDiagnosticVisible", "NONE")
set_bg_only("BufferLineHintDiagnostic", "NONE")
set_bg_only("BufferLineHintSelected", "NONE")
set_bg_only("BufferLineHintVisible", "NONE")
set_bg_only("BufferLineHint", "NONE")
set_bg_only("BufferLineDiagnosticSelected", "NONE")
set_bg_only("BufferLineDiagnostic", "NONE")
set_bg_only("BufferLineNumbersVisible", "NONE")
set_bg_only("BufferLineNumbersSelected", "NONE")
set_bg_only("BufferLineNumbers", "NONE")
set_bg_only("BufferLineBufferSelected", "NONE")
set_bg_only("BufferLineBufferVisible", "NONE")
set_bg_only("BufferLineCloseButtonSelected", "NONE")
set_bg_only("BufferLineCloseButtonVisible", "NONE")
set_bg_only("BufferLineCloseButton", "NONE")
set_bg_only("BufferLineTabClose", "NONE")
set_bg_only("BufferLineTabSelected", "NONE")
set_bg_only("BufferLineGroupLabel", "NONE")
set_bg_only("BufferLineGroupSeparator", "NONE")
set_bg_only("BufferLineTruncMarker", "NONE")
set_bg_only("BufferLineBuffer", "NONE")
set_bg_only("BufferLineDiagnosticVisible", "NONE")
set_bg_only("BufferLineTab", "NONE")
set_bg_only("BufferLineError", "NONE")
set_bg_only("BufferLineModified", "NONE")
set_bg_only("BufferLineSeparator", "NONE")
set_bg_only("BufferLineDuplicate", "NONE")
set_bg_only("BufferLineInfo", "NONE")
set_bg_only("BufferLineFill", "NONE")
set_bg_only("BufferLineBackground", "NONE")
set_bg_only("BufferLineOffsetSeparator", "NONE")
set_bg_only("BufferLinePickVisible", "NONE")
set_bg_only("BufferLinePickSelected", "NONE")
set_bg_only("BufferLineIndicatorVisible", "NONE")
set_bg_only("BufferLineIndicatorSelected", "NONE")
set_bg_only("BufferLineTabSeparatorSelected", "NONE")
set_bg_only("BufferLineTabSeparator", "NONE")
set_bg_only("BufferLineSeparatorVisible", "NONE")
set_bg_only("BufferLineSeparatorSelected", "NONE")
set_bg_only("BufferLinePick", "NONE")
set_bg_only("BufferLineDuplicateVisible", "NONE")
set_bg_only("BufferLineDuplicateSelected", "NONE")
set_bg_only("BufferLineModifiedSelected", "NONE")
set_bg_only("BufferLineModifiedVisible", "NONE")
set_bg_only("BufferLineErrorDiagnosticSelected", "NONE")
set_bg_only("BufferLineErrorDiagnosticVisible", "NONE")
set_bg_only("BufferLineErrorDiagnostic", "NONE")
set_bg_only("BufferLineErrorSelected", "NONE")
set_bg_only("BufferLineErrorVisible", "NONE")
set_bg_only("BufferLineWarningDiagnosticSelected", "NONE")
set_bg_only("BufferLineWarningDiagnosticVisible", "NONE")
set_bg_only("BufferLineWarningDiagnostic", "NONE")
set_bg_only("BufferLineWarningSelected", "NONE")
set_bg_only("BufferLineWarningVisible", "NONE")
set_bg_only("BufferLineWarning", "NONE")
set_bg_only("BufferLineInfoDiagnosticSelected", "NONE")
set_bg_only("BufferLineInfoDiagnosticVisible", "NONE")
set_bg_only("BufferLineInfoDiagnostic", "NONE")
set_bg_only("BufferLineInfoSelected", "NONE")
set_bg_only("BufferLineInfoVisible", "NONE")
set_bg_only("BufferLineHintDiagnosticSelected", "NONE")

set_bg_only("CmpItemAbbr", "NONE")
set_bg_only("CmpItemAbbrDeprecated", "NONE")
set_bg_only("CmpItemAbbrMatch", "NONE")
set_bg_only("CmpItemKind", "NONE")
